name: Git actions practice

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test:
        required: true
        default: "Hello\nhellow2"
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.job1-var.outputs.job1-greeting }}
    steps:
      - name: Setting variable for job1
        id: job1-var
        run: echo "job1-greeting=Hello from job1" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.job2-var.outputs.job2-greeting }}
    steps:
      - name: Setting variable for job2
        id: job2-var
        run: echo "job2-greeting=Hello from job2" >> $GITHUB_OUTPUT
      - name: Printing job1 variable
        run: echo "Message from job1 = ${{ needs.job1.outputs.message }}"

  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Printing job2 variable
        run: echo "Message from job 2 = ${{ needs.job2.outputs.message }}"
